# Generated by Django 3.2.5 on 2021-08-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmodel',
            table='tbl_contact',
        ),
    ]
