from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', Dashboard.as_view(), name = 'dashboard'),
    path('login/', LoginClassBaseView.as_view(), name = 'login'),
    path('logout/', LogoutClassBaseView.as_view(), name = 'logout'),
    path('createcategory/', CategoryCreateClassBaseView.as_view(), name = 'createcategory'),
    path('createproduct/', ProductCreateClassBaseView.as_view(), name = 'createproduct'),
    path('createdough/', CreateViewDough.as_view(), name = 'createdough'),
    path('order/<str:typeoforder>/', order, name = 'createorder'),
    path('doughlist/', ListViewDough.as_view(), name = 'doughlist'),
    path('takeorder/<int:pk>/<str:typeoforder>/', takeorder, name = 'takeorder'),
    path('updateitemqty/<int:pk>/<str:typeoforder>/', ItemQtyUpdateClassBaseView.as_view(), name = 'updateitemqty'),
    path('deleteitem/<int:pk>/<str:typeoforder>/', ItemDeleteClassBaseView.as_view(), name = 'deleteitem'),
    path('checkoutorder/<str:typeoforder>/', checkoutorder, name = 'checkoutorder'),
    path('foodcategory/', CategoryClassBaseView.as_view(), name = 'foodcategory'),
    path('foodlist/<int:category>/', ProductsClassBaseView.as_view(), name = 'foodlist'),
    path('invoice/', InvoiceClassBaseView.as_view(), name = 'invoice'),
    path('orderlist/<int:invoice_no>/', OrdersClassBaseView.as_view(), name = 'orderlist'),
    path('generatereports/', generatereports, name = 'generatereports'),
    path('expenselist/', ExpenseClassBaseView.as_view(), name = 'expenselist'),
    path('createexpense/', ExpenseCreateClassBaseView.as_view(), name = 'createexpense'),
    path('expensereport/', expensereports, name = 'expensereport'),
    path('removeexpense/<int:pk>/', ExpenseDeleteClassBaseView.as_view(), name = 'removeexpense'),
    path('updatecategory/<int:pk>/', CategoryUpdateClassBaseView.as_view(), name = 'updatecategory'),
    path('updatefood/<int:pk>/', ProductUpdateClassBaseView.as_view(), name = 'updatefood'),
    path('updatedough/<int:pk>/', DoughUpdateClassBaseView.as_view(), name = 'updatedough'),
    path('removecategory/<int:pk>/', CategoryDeleteClassBaseView.as_view(), name = 'removecategory'),
    path('removeproduct/<int:pk>/<int:category>/', ProductDeleteClassBaseView.as_view(), name = 'removeproduct'),
    path('itemlogs/<int:pk>/', ProductLogClassbaseView.as_view(), name = 'viewitemlogs'),
    path('viewdoughlogs/<int:pk>/', DoughLogClassbaseView.as_view(), name = 'viewdoughlogs'),
    path('productlog/<int:pk>/', ProductLogCreateClassBaseView.as_view(), name = 'productlog'),
    path('doughlog/<int:pk>/', DoughLogCreateClassBaseView.as_view(), name = 'doughlog'),
    path('removedough/<int:pk>/', DoughDeleteClassBaseView.as_view(), name = 'removedough'),
    path('paid/<int:pk>/', paidStatus, name = 'paid'),
    path('createtable/', TableCreateClassBaseView.as_view(), name = 'tablecreate'),
    path('tablelist/', TableListClassBaseView.as_view(), name = 'tablelist'),
    path('tabledelete/<int:pk>/', TableDeleteClassBaseView.as_view(), name = 'tabledelete'),
    path('creatediscount/', DiscountCreateClassBaseView.as_view(), name = 'discountcreate'),
    path('discountlist/', DiscountListClassBaseView.as_view(), name = 'discountlist'),
    path('discountdelete/<int:pk>/', DiscountDeleteClassBaseView.as_view(), name = 'discountdelete'),
    path('pendingorder/', PendingOrderClassBaseView.as_view(), name = 'pendingorder'),
]
