# Generated by Django 3.2.5 on 2021-07-20 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_product_category',
            },
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Expense Item')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Qty')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_expense',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=250, verbose_name='Order No.')),
                ('order_type', models.CharField(default='local', max_length=10, verbose_name='Order Type')),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Customer Cash')),
                ('discount', models.PositiveIntegerField(default=0, help_text='if applicable', verbose_name='Discount %')),
                ('status', models.CharField(max_length=10, verbose_name='Order Status')),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product Name')),
                ('local_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('online_price', models.DecimalField(decimal_places=2, default=0.0, help_text='if applicable', max_digits=1000000000, verbose_name='Online Price')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Stock(s)')),
                ('date_created', models.DateField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_c_rn', to='apps.categorymodel')),
            ],
            options={
                'db_table': 'tbl_products',
            },
        ),
        migrations.CreateModel(
            name='ItemOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_o_rn', to='apps.ordermodel')),
            ],
            options={
                'db_table': 'tbl_item_orders',
            },
        ),
    ]
