# Generated by Django 3.2.5 on 2021-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='local_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Price'),
        ),
    ]
