# Generated by Django 3.2.5 on 2021-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_productmodel_online_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Optional', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
    ]
