# Generated by Django 3.2.5 on 2021-08-11 02:02

import apps.category.models
import apps.product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', apps.category.models.CharField(default='', error_messages={'unique': 'Category name is already exists.'}, max_length=15, unique=True, verbose_name='Category Name')),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', apps.product.models.CharField(default='', error_messages={'unique': 'Product name is already exists'}, max_length=25, unique=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Price')),
                ('date_created', models.DateField(auto_now=True)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.categorymodel')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file', models.ImageField(upload_to='images/', verbose_name='File')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'tbl_media',
            },
        ),
    ]
