# Generated by Django 3.1.1 on 2020-10-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersmodel',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='careers/'),
        ),
    ]
