# Generated by Django 3.1.1 on 2020-10-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_careersmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newseventmodel',
            options={'ordering': ['-date']},
        ),
    ]
