# Generated by Django 3.2.5 on 2021-08-12 02:58

import apps.vehicle.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_contactmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmodel',
            options={},
        ),
        migrations.AddField(
            model_name='vehicleormodel',
            name='field_office',
            field=apps.vehicle.models.CharField(default='', max_length=250, verbose_name='Field Office'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=apps.vehicle.models.CharField(choices=[('sedan', 'sedan'), ('hatchback', 'hatchback'), ('mpv', 'mpv'), ('suv', 'suv'), ('crossover', 'crossover'), ('van', 'van'), ('pick-up', 'pick-up'), ('hybrid', 'hybrid'), ('4 wheel truck', '4 wheel truck'), ('6 wheel truck', '6 wheel truck'), ('8 wheel truck', '8 wheel truck'), ('10 wheel truck', '10 wheel truck')], help_text='Categorized this vehicle.', max_length=50, verbose_name='Vehicle Type'),
        ),
    ]
