# Generated by Django 3.1.1 on 2020-10-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(error_messages={'unique': 'Employee ID is already exists.'}, max_length=6, null=True, unique=True)),
                ('business_unit', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('employee_position', models.CharField(max_length=50, null=True)),
                ('employee_status', models.CharField(max_length=50, null=True)),
                ('date_hired', models.CharField(max_length=50)),
                ('date_regularized', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee_records',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TimeKeepingDateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employeerecordmodel', to_field='employee')),
            ],
            options={
                'db_table': 'time_keeping_date',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInformationModel',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.employeerecordmodel', to_field='employee')),
                ('civil_status', models.CharField(max_length=50, null=True)),
                ('birthdate', models.CharField(max_length=50)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('third_party_employer', models.CharField(max_length=50, null=True)),
                ('shirt_size', models.CharField(max_length=50, null=True)),
                ('active_status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'employee_information',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TimeLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timekeepingdatemodel')),
            ],
            options={
                'db_table': 'time_logs',
                'ordering': ['-pk'],
            },
        ),
    ]
