# Generated by Django 3.1.1 on 2020-11-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformationmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinformationmodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employeerecordmodel'),
        ),
    ]
