# Generated by Django 3.1.1 on 2020-11-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogsmodel',
            name='employee',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='core.employeerecordmodel', to_field='employee'),
            preserve_default=False,
        ),
    ]
