# Generated by Django 3.1.1 on 2020-11-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_timelogsmodel_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelogsmodel',
            options={'get_latest_by': 'status', 'ordering': ['-pk']},
        ),
    ]
