# Generated by Django 3.1.1 on 2021-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(error_messages={'unique': 'Table name is already exists!'}, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='tableno',
            field=models.CharField(default='Not Available', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='typeoforder',
            field=models.CharField(default='resto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='online_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
