# Generated by Django 3.1.1 on 2021-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(error_messages={'unique': 'Table name is already exists!'}, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
    ]
