# Generated by Django 3.1.1 on 2021-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='tableno',
            field=models.CharField(default='Not Available', max_length=150, null=True),
        ),
    ]
