# Generated by Django 3.1.1 on 2021-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='cash_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='discount',
            field=models.CharField(default='N/D', max_length=3),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='discount_person',
            field=models.CharField(default='N/D', max_length=20),
        ),
    ]
