# Generated by Django 3.2.4 on 2021-06-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_token', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255, verbose_name='Department')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'tbl_deparments',
            },
        ),
        migrations.CreateModel(
            name='JobPositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_token', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255, verbose_name='Job Position')),
                ('description', models.TextField(null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.departmentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='media_token_department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.departmentmodel'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='media_token_jobposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.jobpositionmodel'),
        ),
    ]
