# Generated by Django 3.2.4 on 2021-06-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210622_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQualificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('requirement', 'Requirement'), ('qualification', 'Qualification')], max_length=155)),
                ('jobposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.jobpositionmodel')),
            ],
        ),
    ]
