# Generated by Django 3.2.4 on 2021-06-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_jobqualificationmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobqualificationmodel',
            table='tbl_qualification',
        ),
    ]
