# Generated by Django 3.2.4 on 2021-06-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_jobqualificationmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobpositionmodel',
            table='tbl_jobposition',
        ),
    ]
