# Generated by Django 3.2.4 on 2021-06-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20210624_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='category_apply',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='category_contact_us',
        ),
    ]
