# Generated by Django 3.2.4 on 2021-06-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20210626_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='media_token_jobposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobposition', to='apps.jobpositionmodel'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='media_token_web_contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web', to='apps.webcontentmodel'),
        ),
    ]
