# Generated by Django 3.2.4 on 2021-07-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_jobpositionmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobqualificationmodel',
            name='jobposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_jpositions', to='apps.jobpositionmodel'),
        ),
    ]
