# Generated by Django 3.2.4 on 2021-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_jobqualificationmodel_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontentmodel',
            name='video',
            field=models.FileField(blank=True, default='N/A', null=True, upload_to='n1s_videos/', verbose_name='Video Stream (Optional)'),
        ),
    ]
