# Generated by Django 3.1.1 on 2021-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(default='pending', max_length=120),
        ),
    ]
