# Generated by Django 3.1.1 on 2020-12-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_level',
            field=models.SmallIntegerField(choices=[(1, 'SUPERUSER'), (2, 'ADMIN')], default=2),
        ),
    ]
