# Generated by Django 3.1.1 on 2020-12-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201207_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=150, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folder',
            },
        ),
        migrations.CreateModel(
            name='Racklocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.IntegerField()),
                ('location', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
            options={
                'db_table': 'racklocation',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconcile_stockcode', models.CharField(max_length=150)),
                ('reconcile_description', models.TextField()),
                ('qty', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='auth_level',
            field=models.SmallIntegerField(choices=[(2, 'ADMIN'), (3, 'TABLET / MOBILE USER')], default=2),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('case', models.IntegerField()),
                ('inner_box', models.IntegerField()),
                ('piece', models.IntegerField()),
                ('inventory_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_code', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.folder')),
                ('racklocation', models.ManyToManyField(to='app.Racklocation')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
