# Generated by Django 3.1.1 on 2020-12-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201211_0128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='validation',
            table='product_validation',
        ),
    ]
