# Generated by Django 3.1.1 on 2020-10-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(error_messages={'unique': 'Folder name is already exists.'}, max_length=150, null=True, unique=True)),
                ('type_record', models.CharField(choices=[('ada', 'AUTOMATIC DEDUCTION ADVICE'), ('itequipment', 'IT EQUIPMENT / SFA SELLING TOOLS ASSIGNMENT FORM')], max_length=150, null=True)),
                ('date_record', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['-date_record'],
            },
        ),
        migrations.CreateModel(
            name='ItEquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, null=True)),
                ('custodian', models.CharField(max_length=150, null=True)),
                ('device', models.CharField(max_length=150, null=True)),
                ('mobile', models.CharField(max_length=150, null=True)),
                ('imei', models.CharField(max_length=150, null=True)),
                ('iccid', models.CharField(max_length=150, null=True)),
                ('accessories', models.CharField(max_length=150, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foldermodel')),
            ],
            options={
                'db_table': 'itequipment',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AdaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, null=True)),
                ('fullname', models.CharField(max_length=150, null=True)),
                ('current_user', models.CharField(max_length=150, null=True)),
                ('position', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=150, null=True)),
                ('min', models.CharField(max_length=150, null=True)),
                ('plan', models.CharField(max_length=150, null=True)),
                ('package', models.CharField(max_length=150, null=True)),
                ('handset', models.CharField(max_length=150, null=True)),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foldermodel')),
            ],
            options={
                'db_table': 'ada',
                'ordering': ['-pk'],
            },
        ),
    ]
