# Generated by Django 3.1.1 on 2020-10-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adamodel',
            name='remarks',
        ),
    ]
