# Generated by Django 3.1.1 on 2020-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201021_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='itequipmentmodel',
            name='operation_manager',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
