# Generated by Django 3.1.1 on 2020-10-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itequipmentmodel_operation_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='itequipmentmodel',
            name='is_claim',
            field=models.BooleanField(default=False),
        ),
    ]
