# Generated by Django 3.1.1 on 2021-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210203_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated_person',
            field=models.CharField(default='Not Available', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.CharField(default='Not Available', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='line_manager',
            field=models.CharField(default='Not Available', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='control_no',
            field=models.CharField(default='NO CONTROL NO.', error_messages={'unique': 'Control No. is already exists.'}, max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Control',
        ),
    ]
