# Generated by Django 3.1.1 on 2021-02-03 08:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210203_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='control_no',
            field=models.CharField(blank=True, default=core.models.initializeControlNumber, error_messages={'unique': 'Control No. is already exists.'}, max_length=250, null=True, unique=True),
        ),
    ]
