# Generated by Django 3.1.1 on 2021-02-24 07:47

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.CharField(max_length=150, verbose_name='Entity Item Name')),
                ('qty', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'dough',
            },
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'expense',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('invoice_no', models.CharField(blank=True, default=core.models.increment_invoice_number, max_length=150, null=True)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='not paid', max_length=150, null=True)),
                ('typeoforder', models.CharField(default='resto', max_length=150, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'product_category',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('qty', models.FloatField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcategorymodel')),
                ('dough', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doughmodel', verbose_name='Entity')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductsLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('qty_added', models.IntegerField()),
                ('status', models.CharField(choices=[('ADDED', 'ADD'), ('REMOVED', 'REMOVE')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productsmodel')),
            ],
            options={
                'db_table': 'productlog',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.FloatField(default=1)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoicemodel')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DoughsLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('qty_added', models.FloatField()),
                ('status', models.CharField(choices=[('ADDED', 'ADD'), ('REMOVED', 'REMOVE')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doughmodel')),
            ],
            options={
                'db_table': 'doughlog',
            },
        ),
    ]
