# Generated by Django 3.1.1 on 2021-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicemodel_tableno'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(error_messages={'unique': 'Discount is already exists!'}, max_length=3, null=True, unique=True)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
