# Generated by Django 3.1.1 on 2021-04-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210302_1907'),
        ('core', '0005_auto_20210302_0749'),
    ]

    operations = [
    ]
